before_commands:
    - 'composer install -d api'
    - 'bower install'

filter:
    excluded_paths:
        - api/src/Sententiaregum/Bundle/UserBundle/spec/
        - api/app/
        - api/src/Sententiaregum/Bundle/UserBundle/FeatureContext/
        - api/src/Sententiaregum/Bundle/RedisMQBundle/FeatureContext/

tools:
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['api/src']
    php_loc:
        enabled: true
        excluded_dirs: [api/vendor, api/app, api/features]
    php_cpd:
        enabled: true
        excluded_dirs: [api/vendor, api/app, api/features]
    php_mess_detector: true
    php_analyzer: true
    php_pdepend: true
