before_commands:
    - 'composer install -d api'
    - 'bower install'

filter:
    excluded_paths:
        - app/
        - src/Sententiaregum/CoreDomain/User/Tests/
        - src/Sententiaregum/Bridge/User/Tests/
        - src/Sententiaregum/Bundle/UserBundle/Tests/
        - src/Sententiaregum/Bundle/WebBundle/Tests/
        - src/Sententiaregum/Infrastructure/User/Tests/
        - src/Sententiaregum/Bundle/UserBundle/Behat/

tools:
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, app, features]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, app, features]
    php_mess_detector: true
    php_analyzer: true
    php_pdepend: true
    external_code_coverage: true
