global_exlude_dirs:
    - vendor
    - app
    - web
    - vagrant

exclude_patterns:
    - src/Sententiaregum/Bundle/*Bundle/Tests
    - src/Sententiaregum/CoreBundle/*/Tests
    - devstack.yaml # Exclude vagrant stuff

rules:
    web.default_favicon:
        enabled: false
    web.missing_favicon:
        enabled: false
