exclude_patterns:
    - src/Sententiaregum/Bundle/*Bundle/Tests
    - src/Sententiaregum/CoreBundle/*/Tests
    - devstack.yaml # Exclude vagrant stuff
    - vagrant       # which should not be inspected
    - web           # exlude web stuff
    - app           # app directory

rules:
    web.default_favicon:
        enabled: false
    web.missing_favicon:
        enabled: false
    composer.dependencies_not_installable:
        enabled: false
