global_exlude_dirs:
    - api/vendor
    - api/app
    - api/web

exclude_patterns:
    - api/src/Sententiaregum/Bundle/*Bundle/spec/*
    - api/src/Sententiaregum/Bundle/*Bundle/FeatureContext
    - api/src/Sententiaregum/Bundle/*Bundle/Tests
    - devstack.yaml # Exclude vagrant stuff
    - vagrant       # which should not be inspected
    - web           # exlude web stuff

rules:
    web.default_favicon:
        enabled: false
    web.missing_favicon:
        enabled: false
