language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer update -d api
  - php api/app/check.php

script:
  - cd api
  - bbin/phpspec run
