language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script: rake travis

services:
  - redis-server

script: rake test

after_script: php app/console doctrine:migrations:version 20141018161940 --delete --no-interaction

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: ma27.travis@gmail.com
