language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script: rake deploy

services:
  - redis-server

script: rake test

#after_script:

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: ma27.travis@gmail.com
