language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - printf "\n" | pecl install imagick
  - printf "\n" | pecl install apc
  - mysql -e 'CREATE DATABASE IF NOT EXISTS symfony;'
  - npm install -g bower
  - rake showDependencies
  - rake deploy

services:
  - redis-server

script: rake test

#after_script:

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: ma27.travis@gmail.com
