language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - bower install
  - grunt
  - composer self-update
  - composer update -d api
  - php api/app/check.php
  - mysql -e "CREATE DATABASE IF NOT EXISTS symfony;" -u root
  - echo "use mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user = 'root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - cd api
  - php app/console doctrine:migrations:migrate --no-interaction
  - printf "\n" | pecl install imagick

services:
  - redis-server

script:
  - bin/phpspec run
  - bin/behat --suite=requestToken
  - bin/behat --suite=createAccount
  - bin/behat --suite=redisQueue

after_script:
  - php app/console doctrine:migrations:version 20141018161940 --delete --no-interaction

matrix:
  allow_failures:
    - php: hhvm
