language: php

php:
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures: hhvm

before_script:
    - php api/app/check.php
    - composer self-update
    - composer update -d api

script:
    - api/bin/phpspec run
