language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS symfony;" -u root
  - echo "use mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user = 'root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - ./setup.sh --no-interruption

services:
  - redis-server

script:
  - bin/phpspec run
  - bin/behat

after_script:
  - php app/console doctrine:migrations:version 20141018161940 --delete --no-interaction

matrix:
  allow_failures:
    - php: hhvm
