language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script: rake travis:build

services:
  - redis-server

script: rake test:all

after_script: rake travis:purge

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: ma27.travis@gmail.com
