language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer update -d api
  - php api/app/check.php
  - mysql -e "CREATE DATABASE IF NOT EXISTS symfony;" -u root
  - echo "use mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user = 'root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - php app/console doctrine:migrations:migrate --no-interaction

services:
  - redis-server

script:
  - cd api
  - bin/phpspec run
  - bin/behat

after_script:
  - php app/console doctrine:migrations:version 20141018161940 --delete

matrix:
  allow_failures:
    - php: hhvm
