<?php

namespace Sententiaregum\Bundle\RedisQueueBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class RedisJob extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('sententiaregum:redis:queue-job')
            ->setDescription('Command which refreshed the redis queue');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
 