imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:
        enabled: true
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                mappings:
                    SEN_User:
                        type:      xml
                        is_bundle: false
                        dir:       %kernel.root_dir%/../src/Sententiaregum/Infrastructure/User/Resources/doctrine
                        alias:     SEN_User
                        prefix:    Sententiaregum\CoreDomain\User

# FOS Rest Configuration
fos_rest:
    body_listener: true
    format_listener: true
    view:
        view_response_listener: force
        failed_validation:      HTTP_BAD_REQUEST
        default_engine:         twig
        formats:
            json:  true
            jsonp: true
    format_listener:
        rules:
            - { path: ^/api, priorities: [html, json], fallback_format: ~, prefer_extension: false }
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true

# Sensio Framework Configuration
sensio_framework_extra:
    router:   { annotations: true }
    request:  { converters: true, auto_convert: true }
    view:     { annotations: false }
    cache:    { annotations: true }
    security: { annotations: true }

# Bower Configuration
sp_bower:
    bundles:
        SententiaregumWebBundle:
            json_file:  bower.json
            config_dir: Resources/config
            asset_dir:  ../public/vendor
            cache:
                directory: ../public/cache
    assetic:
        enabled:           true
        nest_dependencies: true

# Sententiaregum Web Configuration
sententiaregum_web:
    form_templates:
        enabled: false

# Sententiaregum User Bundle
sententiaregum_user:
    api_key_authentication:
        enabled: true
