imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    form:  # Disable csrf_protection in a test environment in order to avoid problems using a csrf token in a functional test
        csrf_protection:
            enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# specific test associations
sententiaregum_web:
    form_templates:
        enabled: true
        associations:
            form: ~
