sententiaregum_web:
    resource: "@SententiaregumWebBundle/Controller/"
    type:     annotation
    prefix:   /

sententiaregum_user:
    resource: "@SententiaregumUserBundle/Controller/"
    type:     annotation
    prefix:   /api/auth


