security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        default:
            anonymous: ~
    #firewalls:
    #    network:
    #        pattern:   ^/api/sententiaregum
    #        stateless: true
    #        simple_preauth:
    #            authenticator: sen.user.security.authentication
