imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        name: SEN.SESSION
    fragments:       ~
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Ma27\Sententiaregum\DoctrineMigrations
    table_name: se_doctrine_migration
    name: Sententiaregum Migrations

# User bundle configuration
sententiaregum_user:
    registration:
        defaultRoles: ['ROLE_USER']

# Message queue configuration
sententiaregum_redis_mq:
    queues:
        default: redis::queue::default::

# Entry parser configuration
sententiaregum_entry_parsing:
    tag_delimiter: "#"
    name_delimiter: "@"

# Microblog configuration
sententiaregum_microblogging:
    image_upload_dir: "%kernel.root_dir%/../web/uploads"

# Redis configuration
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            logging: %kernel.debug%
            dsn: %redis_dsn%
