sententiaregum_microblogging:
    resource: "@SententiaregumMicrobloggingBundle/Resources/config/routing.xml"
    prefix:   /api/network

sententiaregum_user:
    resource: "@SententiaregumUserBundle/Resources/config/routing/routing.xml"
    prefix:   /api
