security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        network_api:
            pattern: ^/api/network
            stateless: true
            simple_preauth:
                authenticator: ma27.security.api_key_auth

    access_control:
        - { path: ^/api/network, roles: ROLE_USER }
        - { path: ^/api/network/admin, roles: ROLE_ADMIN }
